import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const base=process.env.FORMA_TEST_URL||'http://localhost:5173';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];
await page.addInitScript(()=>{if(!localStorage.getItem('forma-library'))localStorage.setItem('forma-library',JSON.stringify({version:1,tracks:{},likes:[],playlists:[],events:[],hidden:[],settings:{provider:'audius'},onboarded:false}));});
page.on('pageerror',e=>errors.push(e.message));
// Fixtures never ship with the application. All API/audio requests are intercepted here.
const titles=['Soft Focus','Night Current','Between the Lines','Slow Motion','Morning Light','Far From Home','Blue Hour','Sideways','Quiet Room','Warm Static','Lost in the City','New Perspective','Open Roads','Early Echo','Citylights'];
const tracks=titles.map((title,i)=>({id:'Test'+i,title,user:{id:'Artist'+i,name:['Test Artist One','Test Artist Two','Test Artist Three'][i%3]},genre:['House','Electronic','Ambient'][i%3],mood:i%2?'Peaceful':'Upbeat',duration:120+i*17,tags:'melodic,chill',is_streamable:true,is_downloadable:true,play_count:3000+i*200,favorite_count:500+i*10,artwork:{}}));
function wav(seconds=90){const rate=8000,b=Buffer.alloc(44+rate*2*seconds);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);for(let i=44;i<b.length;i+=2)b.writeInt16LE(Math.round(Math.sin(i/16)*1800),i);return b;}
const audio=wav();
await page.route(/https:\/\/.*\/v1\//,async route=>{
  const u=new URL(route.request().url());
  if(u.pathname.endsWith('/stream')){await route.fulfill({status:200,contentType:'audio/wav',body:audio,headers:{'accept-ranges':'bytes'}});return;}
  let data=tracks;
  if(u.pathname.endsWith('/users/search')){await route.fulfill({json:{data:[{id:'Artist0',name:'Test Artist One',handle:'testone',track_count:4}]}});return;}
  if(u.pathname.endsWith('/search')){const q=u.searchParams.get('query');const g=u.searchParams.get('genre');data=tracks.filter(t=>(!q||`${t.title} ${t.user.name}`.toLowerCase().includes(q.toLowerCase()))&&(!g||t.genre===g));}
  await route.fulfill({json:{data}});
});
try{
  await page.goto(base);
  await page.getByRole('heading',{name:'Как звучит твой мир?'}).waitFor();
  await page.getByRole('button',{name:'House',exact:true}).click();
  await page.getByRole('button',{name:'Ambient',exact:true}).click();
  await page.getByRole('button',{name:'Найти мой ритм'}).click();
  await page.locator('.track-row').first().waitFor();
  assert.equal(await page.locator('.modal').count(),0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await fs.mkdir(path.resolve('artifacts'),{recursive:true});
  await page.screenshot({path:'artifacts/forma-home.png',fullPage:true});
  const firstRow=page.locator('.track-row').first();const firstTitle=await firstRow.locator('.track-name strong').innerText();
  await firstRow.locator('.track-actions button').first().click();
  await page.getByRole('button',{name:'Любимые треки',exact:false}).first().click();
  await page.getByRole('heading',{name:'Любимые треки',exact:true}).waitFor();
  assert.equal(await page.locator('.track-row').count(),1);
  await page.getByRole('button',{name:'Создать плейлист',exact:true}).click();
  await page.getByRole('textbox',{name:'Название плейлиста'}).fill('Вечерний маршрут');
  await page.locator('.modal').getByRole('button',{name:'Создать плейлист'}).click();
  await page.getByRole('heading',{name:'Вечерний маршрут',exact:true}).waitFor();
  await page.getByRole('button',{name:'Любимые треки',exact:false}).first().click();
  await page.locator('.track-actions button').last().click();
  await page.getByRole('button',{name:'Добавить в плейлист',exact:true}).click();
  await page.locator('.playlist-picker').getByRole('button',{name:'Вечерний маршрут'}).click();
  await page.locator('.sidebar-playlists').getByRole('button',{name:'Вечерний маршрут'}).click();
  assert.equal(await page.locator('.track-row').count(),1);
  await page.getByRole('textbox',{name:'Поиск треков и исполнителей'}).fill('Night');
  await page.getByRole('textbox',{name:'Поиск треков и исполнителей'}).press('Enter');
  await page.getByRole('heading',{name:'Поиск «Night»'}).waitFor();
  await page.locator('.best-match').waitFor();
  assert.equal(await page.locator('.track-row').count(),1);
  await page.getByRole('textbox',{name:'Поиск треков и исполнителей'}).fill('Test Artist One');
  await page.locator('.artist-card').first().waitFor();
  await page.locator('.artist-card').first().click();
  await page.getByRole('heading',{name:'Test Artist One',exact:true}).waitFor();
  await page.locator('.track-row').first().waitFor();
  await page.getByRole('button',{name:'Главная',exact:true}).click();
  assert.equal(await page.locator('.mix-card').count(),6);
  await page.locator('.mix-card').filter({hasText:'Тише внутри'}).click();
  await page.getByRole('heading',{name:'Тише внутри',exact:true}).waitFor();
  await page.locator('.track-name').first().click();
  await page.waitForFunction(()=>document.querySelector('audio').currentTime>3.2);
  await page.getByRole('button',{name:'Следующий трек',exact:true}).click();
  await page.waitForTimeout(350);
  assert.ok((await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-library')))).events.some(e=>e.type==='skip'&&e.surface==='mood'&&e.mood==='calm'&&e.seconds>=3));
  await page.getByRole('button',{name:'Пауза',exact:true}).click();
  const volume=page.getByRole('slider',{name:'Громкость',exact:true});
  assert.equal(await volume.getAttribute('step'),'0.001');
  const savedVolume=(await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-library')))).settings.volume;
  const box=await volume.boundingBox();
  await page.mouse.move(box.x+box.width*.3,box.y+box.height/2);await page.mouse.down();
  await page.mouse.move(box.x+box.width*.83,box.y+box.height/2,{steps:24});
  const highVolume=await page.locator('audio').evaluate(a=>a.volume);assert.ok(highVolume>.75);
  await page.mouse.move(box.x+box.width*.37,box.y+box.height/2,{steps:24});
  const liveVolume=await page.locator('audio').evaluate(a=>a.volume);assert.ok(liveVolume>.2&&liveVolume<.5);
  assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-library')))).settings.volume,savedVolume);
  await page.mouse.up();await page.waitForTimeout(350);
  assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-library')))).settings.volume,liveVolume);
  await page.getByRole('button',{name:'Выключить звук',exact:true}).click();assert.equal(await page.locator('audio').evaluate(a=>a.volume),0);
  await page.getByRole('button',{name:'Включить звук',exact:true}).click();assert.equal(await page.locator('audio').evaluate(a=>a.volume),liveVolume);
  await page.getByRole('button',{name:'Главная',exact:true}).click();
  await page.getByRole('button',{name:'Слушать Пульс',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('audio').currentTime>1);
  const old=await page.locator('.now-playing strong').innerText();
  await page.getByRole('button',{name:'Следующий трек',exact:true}).click();
  await page.waitForFunction(old=>document.querySelector('.now-playing strong').textContent!==old,old);
  await page.getByRole('button',{name:'Настройка Пульса',exact:true}).click();
  await page.getByRole('heading',{name:'Твой Пульс. Твой выбор.'}).waitFor();
  await page.getByRole('button',{name:'Предпочитать Ambient',exact:true}).click();
  await page.getByRole('switch',{name:'Только выбранные жанры',exact:true}).click();
  await page.getByRole('textbox',{name:'Исключённые артисты',exact:true}).fill('Test Artist One');
  await page.getByRole('button',{name:'Исключить артиста из Пульса',exact:true}).click();
  await page.getByRole('heading',{name:'Пока нет подходящих треков',exact:true}).waitFor();
  const playingTime=await page.locator('audio').evaluate(a=>a.currentTime);
  await page.waitForFunction(t=>!document.querySelector('audio').paused&&document.querySelector('audio').currentTime>t+.6,playingTime);
  await page.getByRole('button',{name:'Убрать Test Artist One из списка «Исключённые артисты»',exact:true}).click();
  await page.locator('.wave-preview .track-row').first().waitFor();
  const previewTitles=await page.locator('.wave-preview .track-name strong').allTextContents();
  assert.ok(previewTitles.length>0);for(const title of previewTitles)assert.equal(tracks.find(t=>t.title===title).genre,'House');
  await page.getByRole('button',{name:'Для фокуса',exact:true}).click();
  await page.getByRole('slider',{name:'Разнообразие артистов',exact:true}).fill('1');
  await page.getByRole('button',{name:'Только отмеченные',exact:true}).click();
  await page.getByRole('checkbox',{name:'Вечерний маршрут',exact:false}).check();
  await page.getByRole('textbox',{name:'Артисты-ориентиры',exact:true}).fill('Test Artist One');
  await page.getByRole('button',{name:'Добавить артиста-ориентир',exact:true}).click();
  await page.locator('.wave-exclusions summary').click();
  await page.getByRole('button',{name:'Исключить Rock',exact:true}).click();
  await page.setViewportSize({width:1440,height:1500});
  await page.locator('.pulse-settings-modal').evaluate(el=>el.scrollTo(0,0));
  await page.screenshot({path:'artifacts/forma-wave-settings.png',fullPage:true});
  for(const width of [1024,600]){await page.setViewportSize({width,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
  await page.setViewportSize({width:1440,height:1050});
  await page.getByRole('button',{name:'Свернуть настройки Пульса',exact:true}).click();
  await page.getByRole('button',{name:'Пауза',exact:true}).click();
  assert.equal(await page.locator('audio').evaluate(a=>a.paused),true);
  await page.getByRole('button',{name:'Настройки',exact:true}).click();
  await page.getByRole('button',{name:'Океан',exact:false}).click();
  await page.getByRole('button',{name:'Крупный',exact:true}).click();
  assert.equal(await page.locator('.app-shell').getAttribute('data-palette'),'ocean');
  await page.screenshot({path:'artifacts/forma-settings.png',fullPage:true});
  await page.getByRole('switch',{name:'Только скачанная музыка'}).click();
  await page.getByText('Слушаем без интернета.',{exact:false}).waitFor();
  await page.reload();
  assert.equal(await page.locator('.app-shell').getAttribute('data-palette'),'ocean');
  await page.getByRole('button',{name:'Настройка Пульса',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Для концентрации',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.getByRole('button',{name:'Без вокала',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.getByRole('slider',{name:'Разнообразие артистов',exact:true}).inputValue(),'1');
  assert.equal(await page.getByRole('combobox',{name:'Не повторять недавно включённые треки',exact:true}).inputValue(),'6');
  assert.equal(await page.getByRole('switch',{name:'Только выбранные жанры',exact:true}).getAttribute('aria-checked'),'true');
  assert.equal(await page.getByRole('checkbox',{name:'Вечерний маршрут',exact:false}).isChecked(),true);
  const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-library')));
  assert.deepEqual(persisted.settings.excludedGenres,['Rock']);assert.deepEqual(persisted.settings.preferredArtists,['Test Artist One']);
  await page.getByRole('button',{name:'Свернуть настройки Пульса',exact:true}).click();
  await page.getByRole('button',{name:'Любимые треки',exact:false}).first().click();
  assert.equal(await page.locator('.track-name strong').innerText(),firstTitle);
  await page.locator('.sidebar-playlists').getByRole('button',{name:'Вечерний маршрут'}).click();
  assert.equal(await page.locator('.track-row').count(),1);
  await page.setViewportSize({width:1024,height:768});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:600,height:800});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: onboarding, catalogue, likes, playlists, search, six mood playlists with shared feedback, smooth volume/mute persistence, expandable Pulse controls affect preview without stopping playback, presets, preferences survive restart, pause, offline and responsive layout.');
}finally{await browser.close();}
