import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,Download,FileUp,Link,LoaderCircle,Play,X} from 'lucide-react';
import {parseYandexPlaylistURL,parseImportFile,matchLibrary,applyLibraryImport} from '../core/library-import.mjs';

function downloadReport(report) {
  const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));
  const link=document.createElement('a');link.href=url;link.download='Forma-import-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function LibraryImportPage({bridge,state,onChange,onNavigate,onNotify,onPreview,provider='youtube',resume=null}) {
  const [url,setURL]=useState(''),[library,setLibrary]=useState(null),[name,setName]=useState(''),[items,setItems]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(null),[filter,setFilter]=useState('all'),[visible,setVisible]=useState(60);
  const active=useRef(null),fileInput=useRef(null),[resuming,setResuming]=useState(Boolean(resume));
  useEffect(()=>{if(resume?.library){setResuming(true);setLibrary(resume.library);setName(resume.name);setURL(resume.sourceURL);setItems(resume.items||null);}},[resume?.id]);
  useEffect(()=>()=>{if(active.current){active.current.abort();bridge.cancelImport?.();}},[bridge]);
  function acceptLibrary(lib){setResuming(false);setLibrary(lib);setName(lib.name);setItems(null);setProgress(null);setError('');setVisible(60);}
  async function readURL(event){
    event.preventDefault();setError('');
    const controller=new AbortController();active.current=controller;
    try{parseYandexPlaylistURL(url);setBusy('read');const lib=await bridge.yandexPlaylist(url);if(!controller.signal.aborted)acceptLibrary(lib);}
    catch(e){if(!controller.signal.aborted)setError(e.message);}finally{if(!controller.signal.aborted)setBusy('');}
  }
  async function readFile(event){
    const file=event.target.files[0];event.target.value='';if(!file)return;
    try{if(file.size>10*1024**2)throw new Error('Файл должен быть меньше 10 МБ.');const bytes=await file.arrayBuffer();let text=new TextDecoder().decode(bytes);if(text.includes('\uFFFD'))text=new TextDecoder('windows-1251').decode(bytes);acceptLibrary(parseImportFile(text,file.name));}catch(e){setError(e.message);}
  }
  async function match(){
    const controller=new AbortController();active.current=controller;setBusy('match');setError('');setProgress({completed:0,total:library.tracks.length,current:''});setItems(null);
    try{const found=await matchLibrary(library,bridge.request,{signal:controller.signal,onProgress:p=>{if(!controller.signal.aborted)setProgress(p);},localTracks:Object.values(state.tracks)});if(!controller.signal.aborted){setItems(found);setFilter('all');setVisible(60);}}
    catch(e){if(!controller.signal.aborted)setError(e.message);}finally{if(!controller.signal.aborted)setBusy('');}
  }
  function cancel(){active.current?.abort();bridge.cancelImport?.();setBusy('');setProgress(null);}
  function select(index,selectedId){setItems(old=>old.map((item,i)=>i===index?{...item,selectedId:selectedId||null}:item));}
  function commit(){try{let playlistId;onChange(s=>{const next=applyLibraryImport(s,library,items,{name:name.trim()||library.name,id:resuming?resume?.id:undefined,preserveUnmatched:resuming});playlistId=next.playlists.at(-1).id;if(resuming)next.importRequests=next.importRequests.map(r=>r.id===resume.id?{...r,status:'complete',items}:r);return next;});onNotify('Плейлист перенесён. Пульс уже учитывает твой выбор.');onNavigate(`playlist:${playlistId}`);}catch(e){setError(e.message);}}
  const selected=items?.filter(i=>i.selectedId).length||0,unresolved=items?.filter(i=>!i.selectedId).length||0;
  const filtered=items?.map((item,index)=>({item,index})).filter(({item})=>filter==='all'||filter==='unresolved'&&!item.selectedId||filter==='selected'&&item.selectedId)||[];
  const report=()=>({name,sourceURL:library.sourceURL,at:Date.now(),entries:items.map(i=>({source:i.source,trackId:i.selectedId,status:i.selectedId?'matched':i.status}))});
  return <>
    <div className="page-intro"><div><span className="eyebrow">ПУСТЬ ЛЮБИМОЕ ОСТАНЕТСЯ С ТОБОЙ</span><h1>Музыка переезжает.</h1><p>Перенеси публичный плейлист из Яндекс Музыки и дай своему Пульсу точку опоры.</p></div><ArrowUpRight className="intro-icon" size={46} strokeWidth={1}/></div>
    <section className="settings-card import-source"><div className="card-title"><h2>Ссылка на плейлист</h2><Link size={22}/></div><p>В Яндекс Музыке открой плейлист → «Поделиться» → «Скопировать ссылку». Плейлист должен быть публичным.</p><form onSubmit={readURL} className="import-url"><input className="text-input" aria-label="Ссылка на публичный плейлист" placeholder="https://music.yandex.ru/playlists/…" value={url} onChange={e=>setURL(e.target.value)} required disabled={Boolean(busy)}/><button className="button button-primary" disabled={Boolean(busy)||!url.trim()}>{busy==='read'?<LoaderCircle size={18} className="spin"/>:<ArrowRight size={18}/>}Прочитать плейлист</button></form><div className="import-fallback"><input ref={fileInput} type="file" accept=".json,.csv,.txt,.tsv" hidden onChange={readFile}/><button className="text-link" disabled={Boolean(busy)} onClick={()=>fileInput.current.click()}><FileUp size={17}/>Или загрузить список из файла</button><span>JSON, CSV или «Исполнитель — Название»</span></div></section>
    {error&&<div className="network-banner" role="alert"><span>{error}</span><button aria-label="Скрыть ошибку импорта" onClick={()=>setError('')}><X size={17}/></button></div>}
    {busy&&<div className="settings-card import-progress" role="status"><div className="card-title"><h2>{busy==='read'?'Читаем плейлист…':'Ищем совпадения…'}</h2><button className="button button-outline" onClick={cancel}>Отменить</button></div>{progress&&<><p>{progress.completed} из {progress.total} · {progress.current}</p><progress max={progress.total} value={progress.completed}/></>}<p>{busy==='read'?'Получаем названия и исполнителей.':'Большие плейлисты могут занять несколько минут. Точный артист и версия трека важнее похожего названия.'}</p></div>}
    {library&&!busy&&!items&&<section className="settings-card import-preview"><span className="eyebrow">ПЛЕЙЛИСТ ПРОЧИТАН</span><h2>{library.name}</h2><p>{library.tracks.length} треков. Теперь найдём доступные версии в {provider==='youtube'?'YouTube':'Audius'}. Совпадения можно будет проверить перед сохранением.</p><div className="import-preview-list">{library.tracks.slice(0,5).map((t,i)=><div key={i}><span>{i+1}</span><strong>{t.title}</strong><small>{t.artists.join(', ')||'Исполнитель не указан'}</small></div>)}{library.tracks.length>5&&<p>И ещё {library.tracks.length-5} треков</p>}</div><button className="button button-primary" onClick={match}><ArrowRight size={17}/>Найти совпадения</button></section>}
    {items&&!busy&&<>
      <section className="settings-card import-summary"><div className="card-title"><div><span className="eyebrow">ПРОВЕРЬ СОВПАДЕНИЯ</span><h2>{library.name}</h2></div><Check size={25}/></div><div className="profile-stats"><div><strong>{items.length}</strong><span>в исходном плейлисте</span></div><div><strong>{selected}</strong><span>подтверждено</span></div><div><strong>{unresolved}</strong><span>без выбранной версии</span></div></div><p>Каталоги отличаются. Каверы и ремиксы не выбираются автоматически вместо оригинала. Не перенесённые треки сохранятся в отчёте.</p><label className="field-label" htmlFor="import-name">Название нового плейлиста</label><input id="import-name" className="text-input" maxLength="100" value={name} onChange={e=>setName(e.target.value)}/><div className="import-buttons"><button className="button button-primary" disabled={!selected&&!resuming} onClick={commit}>{resuming?'Сохранить плейлист':'Создать плейлист'} · {selected} <ArrowRight size={17}/></button><button className="button button-outline" onClick={()=>downloadReport(report())}><Download size={17}/>Скачать отчёт</button><button className="text-link" onClick={match}>Повторить сопоставление</button></div></section>
      <div className="search-tabs">{[['all','Все'],['unresolved','Требуют внимания'],['selected','Выбрано']].map(([id,label])=><button key={id} className={filter===id?'selected':''} aria-pressed={filter===id} onClick={()=>{setFilter(id);setVisible(60);}}>{label}</button>)}</div>
      <div className="import-review-list">{filtered.slice(0,visible).map(({item,index})=><div className={`import-row ${item.selectedId?'confirmed':''}`} key={index}><div className="import-original"><small>ЯНДЕКС МУЗЫКА</small><strong>{item.source.title}</strong><p>{item.source.artists.join(', ')||'Исполнитель не указан'}</p></div><ArrowRight size={18}/><div className="import-match"><label htmlFor={`match-${index}`} className="field-label">{provider==='youtube'?'YOUTUBE':'AUDIUS'} {item.status==='matched'?'· точное совпадение':item.status==='error'?'· ошибка поиска':item.candidates.length?'· проверь версию':'· не найдено'}</label><select id={`match-${index}`} aria-label={`Версия для ${item.source.title}`} value={item.selectedId||''} onChange={e=>select(index,e.target.value)}><option value="">Не переносить</option>{item.candidates.map(c=><option key={c.track.id} value={c.track.id}>{c.track.artist} — {c.track.title} ({Math.round(c.score*100)}%)</option>)}</select></div>{item.selectedId&&<button className="icon-button" aria-label={`Проверить ${item.source.title}`} title="Послушать выбранную версию" onClick={()=>onPreview(item.candidates.find(c=>c.track.id===item.selectedId).track)}><Play size={17}/></button>}</div>)}</div>{filtered.length>visible&&<button className="button button-outline load-more" onClick={()=>setVisible(v=>v+60)}>Ещё {Math.min(60,filtered.length-visible)} треков</button>}
    </>}
    {(state.imports||[]).length>0&&<><div className="section-heading"><h2>Предыдущие переносы</h2></div><div className="import-history">{[...state.imports].reverse().map(r=><div key={r.id}><div><strong>{r.name}</strong><p>{r.entries.filter(e=>e.trackId).length} из {r.entries.length} треков · {new Date(r.at).toLocaleDateString('ru-RU')}</p></div><button className="button button-outline" onClick={()=>downloadReport(r)}><Download size={16}/>Отчёт</button></div>)}</div></>}
    <p className="settings-note">Перенос читает список треков, а затем находит версии в каталоге Forma. Музыка из Яндекса не скачивается. Если Яндекс ограничивает доступ к публичной ссылке, можно импортировать файл со списком.</p>
  </>;
}
