import React,{useEffect,useState} from 'react';
export default function SyncSettings({bridge}){
  const [status,setStatus]=useState({enabled:false,devices:[]}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{bridge.syncStatus?.().then(setStatus).catch(e=>setError(e.message));},[bridge]);
  useEffect(()=>{if(!status.enabled)return;const timer=setInterval(()=>bridge.syncStatus().then(setStatus).catch(()=>{}),10000);return()=>clearInterval(timer);},[bridge,status.enabled]);
  async function run(fn){setBusy(true);setError('');try{setStatus(await fn());}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(!bridge.desktop)return null;
  return <section className="settings-card" style={{marginBottom:24}}><h2>iPhone и ПК</h2><p>Подключи оба устройства к одной Wi-Fi сети. Избранное, плейлисты, история и основные настройки Пульса синхронизируются, пока Forma открыта на ПК.</p><button className="button button-primary" disabled={busy} onClick={()=>run(status.enabled?bridge.syncStop:bridge.syncStart)}>{busy?'Подключаем…':status.enabled?'Выключить синхронизацию':'Подключить iPhone'}</button>{status.enabled&&<><p className="settings-note">На iPhone открой «Настройки → Синхронизация с ПК» и вставь код подключения. Разреши Forma доступ к частной сети в брандмауэре Windows.</p>{status.pairing?<><textarea className="text-input" aria-label="Код подключения iPhone" readOnly value={status.pairing} rows={3} onFocus={e=>e.target.select()}/><p className="settings-note">Код действует 5 минут и используется один раз. Соединение зашифровано.</p></>:<p>Код уже использован или истёк.</p>}<button className="button button-outline" disabled={busy} onClick={()=>run(bridge.syncPair)}>Новый код</button><p>{status.devices.length?`Подключено: ${status.devices.map(d=>d.name).join(', ')}`:'Ожидаем iPhone'}</p>{status.devices.length>0&&<button className="text-link" onClick={()=>run(bridge.syncForget)}>Отключить все телефоны</button>}</>}{error&&<p role="alert">{error}</p>}<p className="settings-note">YouTube-треки доступны на обоих устройствах. Локальные аудиофайлы и ключи API остаются на ПК. Синхронизация не требует аккаунта или подписки.</p></section>;
}
