import React,{useState} from 'react';
import {SlidersHorizontal,Check,X,Plus,Heart,RefreshCw,AudioLines,Sparkles,Users,ListMusic,Play,RotateCcw} from 'lucide-react';
import {WAVE_GENRES,MOODS,DEFAULT_WAVE_SETTINGS,waveSettings,fold} from '../core/wave-settings.mjs';

function Choice({label,value,options,onChange}){return <div className="wave-choice"><h3>{label}</h3><div className="wave-choice-buttons" aria-label={label}>{options.map(([id,name])=><button key={id} aria-pressed={value===id} className={value===id?'selected':''} onClick={()=>onChange(id)}>{name}</button>)}</div></div>;}
function ArtistList({label,description,values,action,onAdd,onRemove}){
  const [name,setName]=useState('');
  return <div className="wave-artist-list"><h3>{label}</h3><p>{description}</p><form onSubmit={e=>{e.preventDefault();if(name.trim()){onAdd(name.trim());setName('');}}}><input className="text-input" aria-label={label} maxLength="80" placeholder="Имя исполнителя" value={name} onChange={e=>setName(e.target.value)}/><button className="icon-button" aria-label={action} title={action} disabled={!name.trim()||values.length>=40}><Plus size={20}/></button></form><div className="wave-artist-chips">{values.map(a=><span key={a}>{a}<button aria-label={`Убрать ${a} из списка «${label}»`} onClick={()=>onRemove(a)}><X size={14}/></button></span>)}</div></div>;
}
export default function WaveSettingsPage({settings,playlists,onChange,recommendations,renderTracks,onRefresh,loading,canRefresh,onPlay}){
  const s=waveSettings(settings);
  function toggleGenre(genre,exclude=false){const key=exclude?'excludedGenres':'genres',opposite=exclude?'genres':'excludedGenres';const patch={[key]:s[key].includes(genre)?s[key].filter(g=>g!==genre):[...s[key],genre],[opposite]:s[opposite].filter(g=>g!==genre)};if(!patch.genres.length)patch.genreMode='prefer';onChange(patch);}
  function addArtist(key,artist){const opposite=key==='preferredArtists'?'blockedArtists':'preferredArtists';onChange({[key]:[...s[key].filter(a=>fold(a)!==fold(artist)),artist],[opposite]:s[opposite].filter(a=>fold(a)!==fold(artist))});}
  const preview=recommendations.slice(0,5);
  return <>
    <div className="page-intro wave-settings-intro"><div><span className="eyebrow">МУЗЫКА ПО ТВОИМ ПРАВИЛАМ</span><h1>Твой Пульс. Твой выбор<span>.</span></h1><p>Задай направление. Пульс соединит твои настройки с тем, что ты слушаешь и сохраняешь.</p></div><SlidersHorizontal className="intro-icon" size={42} strokeWidth={1}/></div>
    <div className="wave-presets"><span>Быстрый старт</span>{[['Сбалансированная',{discovery:0.3,mood:'any',energy:'any',vocals:'any',artistDiversity:0.6,repeatCooldown:2}],['Для фокуса',{discovery:0.25,mood:'focus',energy:'low',vocals:'instrumental',artistDiversity:0.5,repeatCooldown:6}],['Новые имена',{discovery:0.85,mood:'any',energy:'any',vocals:'any',artistDiversity:1,repeatCooldown:24}]].map(([name,patch])=><button key={name} onClick={()=>onChange(patch)}><Sparkles size={15}/>{name}</button>)}</div>
    <section className="settings-card wave-genres-card"><div className="card-title"><div><span className="eyebrow">01 / НАПРАВЛЕНИЯ</span><h2>Больше того, что любишь</h2></div><AudioLines size={25}/></div><p>Выбери предпочитаемые жанры. Прослушивания продолжат уточнять твой вкус.</p><div className="genre-chips wave-genre-chips">{WAVE_GENRES.map(g=><button key={g} aria-label={`Предпочитать ${g}`} aria-pressed={s.genres.includes(g)} className={s.genres.includes(g)?'selected':''} onClick={()=>toggleGenre(g)}>{g}{s.genres.includes(g)&&<Check size={14}/>}</button>)}</div><div className="setting-row wave-strict"><div><strong>Только выбранные жанры</strong><p>{s.genres.length?'Треки без подходящего направления не попадут в Пульс':'Сначала выбери хотя бы один жанр'}</p></div><button role="switch" aria-label="Только выбранные жанры" aria-checked={s.genreMode==='strict'} disabled={!s.genres.length} className={`toggle ${s.genreMode==='strict'?'on':''}`} onClick={()=>onChange({genreMode:s.genreMode==='strict'?'prefer':'strict'})}><i/></button></div><details className="wave-exclusions"><summary>Жанры, которые не хочется слышать <span>{s.excludedGenres.length||''}</span></summary><div className="genre-chips wave-genre-chips">{WAVE_GENRES.map(g=><button key={g} aria-label={`Исключить ${g}`} aria-pressed={s.excludedGenres.includes(g)} className={s.excludedGenres.includes(g)?'selected excluded':''} onClick={()=>toggleGenre(g,true)}>{g}{s.excludedGenres.includes(g)&&<X size={14}/>}</button>)}</div></details></section>
    <div className="wave-settings-grid"><section className="settings-card"><div className="card-title"><div><span className="eyebrow">02 / КАК ЗВУЧАТЬ</span><h2>Настроение и характер</h2></div><Sparkles size={24}/></div><Choice label="Настроение" value={s.mood} options={MOODS.map(m=>[m.id,m.name])} onChange={mood=>onChange({mood})}/><Choice label="Энергия" value={s.energy} options={[["any","Любая"],["low","Мягче"],["medium","Умеренно"],["high","Бодрее"]]} onChange={energy=>onChange({energy})}/><Choice label="Вокал" value={s.vocals} options={[["any","Любой"],["instrumental","Без вокала"],["vocal","С вокалом"]]} onChange={vocals=>onChange({vocals})}/><p className="settings-note">Это предпочтения, а не жёсткие ограничения. У YouTube не всегда есть жанры и характеристики: направление поиска помогает подбору, но может быть неточным.</p></section>
    <section className="settings-card"><div className="card-title"><div><span className="eyebrow">03 / ЗНАКОМОЕ И НОВОЕ</span><h2>Ритм открытий</h2></div><Users size={24}/></div><div className="wave-slider-title"><h3>Доля открытий</h3><span>{Math.round(s.discovery*100)}%</span></div><div className="discovery-labels"><span>Ближе к знакомому</span><span>Больше нового</span></div><input className="slider" type="range" aria-label="Доля открытий" min="0" max="1" step="0.05" value={s.discovery} onChange={e=>onChange({discovery:Number(e.target.value)})}/><div className="wave-slider-title"><h3>Разнообразие артистов</h3><span>{Math.round(s.artistDiversity*100)}%</span></div><p>Увеличь, чтобы один исполнитель реже занимал несколько мест подряд.</p><input className="slider" type="range" aria-label="Разнообразие артистов" min="0" max="1" step="0.05" value={s.artistDiversity} onChange={e=>onChange({artistDiversity:Number(e.target.value)})}/><label className="field-label" htmlFor="wave-repeat">Не повторять недавно включённые треки</label><select id="wave-repeat" className="wave-select" value={s.repeatCooldown} onChange={e=>onChange({repeatCooldown:Number(e.target.value)})}>{[[0,'Без интервала'],[0.5,'30 минут'],[2,'2 часа'],[6,'6 часов'],[24,'Сутки'],...(![0,0.5,2,6,24].includes(s.repeatCooldown)?[[s.repeatCooldown,`${s.repeatCooldown} ч`]]:[])].map(([value,name])=><option key={value} value={value}>{name}</option>)}</select><div className="setting-row"><div><strong>Играть сохранённые треки</strong><p>Любимое и плейлисты могут звучать в Пульсе</p></div><button role="switch" aria-label="Играть сохранённые треки" aria-checked={s.includeLibrary} className={`toggle ${s.includeLibrary?'on':''}`} onClick={()=>onChange({includeLibrary:!s.includeLibrary})}><i/></button></div></section></div>
    <section className="settings-card wave-artists-card"><div className="card-title"><div><span className="eyebrow">04 / ИСПОЛНИТЕЛИ</span><h2>Кого хочется слышать</h2></div><Heart size={24}/></div><div className="wave-settings-grid"><ArtistList label="Артисты-ориентиры" description="Их музыка получает дополнительный приоритет." action="Добавить артиста-ориентир" values={s.preferredArtists} onAdd={artist=>addArtist('preferredArtists',artist)} onRemove={artist=>onChange({preferredArtists:s.preferredArtists.filter(a=>a!==artist)})}/><ArtistList label="Исключённые артисты" description="Не попадут в Пульс. Вручную их можно слушать." action="Исключить артиста из Пульса" values={s.blockedArtists} onAdd={artist=>addArtist('blockedArtists',artist)} onRemove={artist=>onChange({blockedArtists:s.blockedArtists.filter(a=>a!==artist)})}/></div></section>
    <section className="settings-card wave-library-card"><div className="card-title"><div><span className="eyebrow">05 / ОСНОВА ТВОЕГО ВКУСА</span><h2>Какие плейлисты учитывать</h2></div><ListMusic size={25}/></div><p>Любимые треки и история остаются ориентирами. Для плейлистов можно выбрать отдельные источники вкуса.</p><Choice label="Плейлисты для рекомендаций" value={s.playlistSource} options={[["all","Все плейлисты"],["selected","Только отмеченные"]]} onChange={playlistSource=>onChange({playlistSource})}/>{s.playlistSource==='selected'&&<div className="wave-seed-playlists">{playlists.length?playlists.map(p=><label key={p.id}><input type="checkbox" checked={s.seedPlaylistIds.includes(p.id)} onChange={()=>onChange({seedPlaylistIds:s.seedPlaylistIds.includes(p.id)?s.seedPlaylistIds.filter(id=>id!==p.id):[...s.seedPlaylistIds,p.id]})}/><ListMusic size={18}/><span>{p.name}<small>{p.trackIds.length} треков</small></span></label>):<p>Пока нет плейлистов. Добавь свой или перенеси его из Яндекс Музыки.</p>}{!playlists.some(p=>s.seedPlaylistIds.includes(p.id))&&<p className="settings-note">Плейлисты сейчас не участвуют в профиле. Пульс учитывает любимые треки, историю и настройки.</p>}</div>}</section>
    <section className="wave-preview"><div className="section-heading"><div><span className="eyebrow">УЖЕ С ТВОИМИ НАСТРОЙКАМИ</span><h2>Предпросмотр Пульса</h2><p>Настройки сохраняются автоматически. Текущий трек продолжит играть; следующий выбор уже их учтёт.</p></div><button className="button button-outline" disabled={!canRefresh||loading} onClick={onRefresh}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Обновляем…':'Обновить каталог'}</button></div>{preview.length?<>{renderTracks(preview.map(r=>r.track),{reasons:Object.fromEntries(preview.map(r=>[r.track.id,r.reason]))})}<button className="button button-primary wave-listen" onClick={onPlay}><Play size={17} fill="currentColor"/>Слушать Пульс</button></>:<div className="empty"><AudioLines size={30}/><h3>{loading?'Находим музыку под настройки':'Пока нет подходящих треков'}</h3><p>Обнови каталог или смягчи ограничения. Пульс соблюдает исключения жанров и артистов.</p></div>}</section>
    <div className="wave-settings-footer"><span><Check size={15}/>Сохраняется на этом устройстве</span><button className="text-link" onClick={()=>onChange(structuredClone(DEFAULT_WAVE_SETTINGS))}><RotateCcw size={15}/>Сбросить настройки Пульса</button></div>
  </>;
}
